### PR TITLE
update code snippets for ansible 2.8

### PR DESCRIPTION
**Pull request by yungezz**
## Summary

update  ansible code snippets for 2.8
## Issue Type

- New Feature

### CODE REVIEW

**Comment by patrickeasters** [comment]
@yungezz any chance we can get a new release tagged? It'd be nice to have these new snippets available.

**Comment by yungezz** [comment]
@mybayern1974 would you like to look at the issue?

**Comment by nschende-mort** [comment]
2.9 is out now. is there a way to manually go about updating the snippets in the plugin?

**Comment by nschende-mort** [comment]
Is there some way I can help with this? Is testing needed? A way to manually update the snippet within code?

**Comment by nschende-mort** [comment]
Bump. Is there a way I could assist with getting this rolled in?  Is there a manual way to update the snippets? Would like to help but but am starting to wonder if this plugin has been abandoned?

**Pull request merged**
